services:
  gitlab:
    image: gitlab/gitlab-ce:17.8.7-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8000'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
      GITLAB_ROOT_PASSWORD: 'B3!f3TPnNvLR1F1I'
    ports:
      - '8000:8000'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '512m'
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "8.0"
          memory: "16g"
        reservations:
          cpus: "8.0"
          memory: "16g"