services:
  database:
    image: postgres:15
    container_name: instantiate_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: instantiate
      POSTGRES_USER: instantiate
      POSTGRES_PASSWORD: instantiate
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: