import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting-started/installation'],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        {
          type: 'category',
          label: 'Orchestrators',
          items: [
            'configuration/orchestrators/configuration-docker',
            'configuration/orchestrators/configuration-swarm',
            'configuration/orchestrators/configuration-kubernetes',
          ],
        },
        'configuration/environment-variables',
        'configuration/template-variables',
        'configuration/prebuild-commands',
        'configuration/service-from-git'
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: ['examples/front-and-back'],
    },
  ],
};

export default sidebars;
